// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrepqXQxzAJRdcPlSHIR__2VfDQIgZWP8',
    appId: '1:635969494358:web:47805600923078e3cc4af7',
    messagingSenderId: '635969494358',
    projectId: 'intern-challenge-ngabroger',
    authDomain: 'intern-challenge-ngabroger.firebaseapp.com',
    storageBucket: 'intern-challenge-ngabroger.firebasestorage.app',
    measurementId: 'G-NRHZ1P82C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK-19QWF721CuJnxIsF_WmVTlKKNNS1-E',
    appId: '1:635969494358:android:38a09d6406d679eccc4af7',
    messagingSenderId: '635969494358',
    projectId: 'intern-challenge-ngabroger',
    storageBucket: 'intern-challenge-ngabroger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVgoSNuUS5OhkTD4wLp_cSwBsgJLl9jBo',
    appId: '1:635969494358:ios:5c6a294472a1de7fcc4af7',
    messagingSenderId: '635969494358',
    projectId: 'intern-challenge-ngabroger',
    storageBucket: 'intern-challenge-ngabroger.firebasestorage.app',
    iosBundleId: 'com.example.flutterInternChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVgoSNuUS5OhkTD4wLp_cSwBsgJLl9jBo',
    appId: '1:635969494358:ios:5c6a294472a1de7fcc4af7',
    messagingSenderId: '635969494358',
    projectId: 'intern-challenge-ngabroger',
    storageBucket: 'intern-challenge-ngabroger.firebasestorage.app',
    iosBundleId: 'com.example.flutterInternChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrepqXQxzAJRdcPlSHIR__2VfDQIgZWP8',
    appId: '1:635969494358:web:09212fdd19f2f29dcc4af7',
    messagingSenderId: '635969494358',
    projectId: 'intern-challenge-ngabroger',
    authDomain: 'intern-challenge-ngabroger.firebaseapp.com',
    storageBucket: 'intern-challenge-ngabroger.firebasestorage.app',
    measurementId: 'G-LQGNZ42TJZ',
  );
}
